### PR TITLE
Make Docker image drastically smaller

### PR DESCRIPTION
**Pull request by emanuelpalm**
Essentially, I replaced the Docker base image with one that only comes with Alpine Linux, Nginx (web server) and Perl. I created a little Perl script that reads environment variables settable via Docker and makes them available via the /config.json endpoint while the container is running. That means that the build step is no longer required to set the Docker environment variables. I needed to make some modest changes to the network services to make this work.

### CODE REVIEW

**Comment by emanuelpalm** [comment]
I mentioned this PR in arrowhead-f/core-java-spring/issues/175.

**Comment by tsvetlin** [comment]
I'll it in the morning :) Thank you for the contribution!

**Comment by emanuelpalm** [comment]
Actually, I realized that these changes might interfere with the development environment, even though they might be appropriate for production builds. I'll fix it.

**Comment by tsvetlin** [comment]
Thanks. What I saw, that we are losing the ability to start the container with different environmental variables. Currently when we start the container, it will build the application (this is why it takes that much time, but we can customize env. Now we prebuild the application with env and we cant modify them later. Thus we cannot ship the application to others. 

The main problem is, that in browsers there are no environmental variables.

**Pull request closed without merging**
